modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="GPL"
[[mods]] #mandatory
modId="skyblock" #mandatory
version="${file.jarVersion}" #mandatory
displayName="SkyBlock" #mandatory
description='''
Just some WorldTypes for The Void
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.skyblock]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.skyblock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17]"
    ordering="NONE"
    side="BOTH"
